
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header/Header';
import { CartProvider } from '@/context/CartContext';
import { AuthProvider } from "@/context/AuthContext";
import Head from 'next/head';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="/favicon.ico" />
                <title>Creative Hands Website</title>
            </Head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <AuthProvider>
                    <CartProvider>
                    <main className="page-container">
                        <Header />
                        {children}
                    </main>
                    </CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
